version: '3.7'
services: 

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  petclinic:
     depends_on:
       - mysql
     image: arey/springboot-petclinic
     ports:
       - "8080:8080"
     environment:
       - SPRING_PROFILES_ACTIVE=mysql,prod
      #  - spring.profiles.active=mysql.prod
       - spring.datasource.url=jdbc:mysql://mysql:3306/petclinic?useUnicode=true
       - spring.datasource.username=petclinic
       - spring.datasource.password=petclinic
       - spring.datasource.initialization-mode=always
       - spring.datasource.initialization=true
