version: '2.1'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 24
    networks:
      consul_app-network:
        ipv4_address: 10.20.0.5

  consul-client:
    image: consul:1.7.2
    container_name: mysql-agent
    volumes:
      - ./config:/consul/config
    command: agent -node=mysql -join=10.20.0.250
    networks:
      consul_app-network:
        ipv4_address: 10.20.0.6

networks:
  consul_app-network:
    external: true
